<?php

namespace Database\Seeders;

use App\Models\Dish;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class DishSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        Dish::insert([
            [
                'name' => 'Combo Đại Tiệc',
                'description' => 'Combo gồm nhiều món đặc sắc cho nhóm đông người.',
                'image_url' => null,
                'status' => 'active',
                'is_featured' => true,
                'category_id' => 2,
                'original_price' => 450000.00,
                'selling_price' => 500000.00,
                'tags' => json_encode(['combo', 'best-seller']),
                'unit' => 'plate',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Món mới: Cá hồi sốt cam',
                'description' => 'Cá hồi tươi sốt cam, vị chua ngọt lạ miệng.',
                'image_url' => null,
                'status' => 'active',
                'is_featured' => true,
                'category_id' => 3,
                'original_price' => 180000.00,
                'selling_price' => 170000.00,
                'tags' => json_encode(['món mới', 'đặc sản']),
                'unit' => 'plate',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Rượu mơ 9chum (500ml)',
                'description' => 'Rượu mơ 9chum được làm từ mơ tươi, hương vị thơm ngon, nồng độ vừa phải.',
                'image_url' => null,
                'status' => 'active',
                'is_featured' => true,
                'category_id' => 4,
                'original_price' => 120000.00,
                'selling_price' => 100000.00,
                'tags' => json_encode(['best-seller', 'đồ uống']),
                'unit' => 'plate',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Dê hấp tía tô',
                'description' => 'Thịt dê tươi hấp cùng lá tía tô, thơm ngon bổ dưỡng.',
                'image_url' => null,
                'status' => 'active',
                'is_featured' => false,
                'category_id' => 5,
                'original_price' => 150000.00,
                'selling_price' => 140000.00,
                'tags' => json_encode(['dê tươi', 'đặc sản']),
                'unit' => 'plate',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Salad cá ngừ',
                'description' => 'Salad rau củ tươi, cá ngừ và sốt đặc biệt.',
                'image_url' => null,
                'status' => 'active',
                'is_featured' => true,
                'category_id' => 6,
                'original_price' => 90000.00,
                'selling_price' => 85000.00,
                'tags' => json_encode(['salad', 'nộm']),
                'unit' => 'plate',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Rau muống xào tỏi',
                'description' => 'Rau muống tươi xào tỏi, giòn ngon.',
                'image_url' => null,
                'status' => 'active',
                'is_featured' => false,
                'category_id' => 7,
                'original_price' => 50000.00,
                'selling_price' => 45000.00,
                'tags' => json_encode(['rau xanh']),
                'unit' => 'plate',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Thiết bàn đặc biệt',
                'description' => 'Set thiết bàn gồm nhiều món nhậu đặc sắc.',
                'image_url' => null,
                'status' => 'active',
                'is_featured' => true,
                'category_id' => 8,
                'original_price' => 380000.00,
                'selling_price' => 400000.00,
                'tags' => json_encode(['thiết bàn', 'best-seller']),
                'unit' => 'plate',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Ba chỉ nướng mật ong',
                'description' => 'Ba chỉ heo nướng mật ong, thơm ngọt, mềm.',
                'image_url' => null,
                'status' => 'active',
                'is_featured' => false,
                'category_id' => 9,
                'original_price' => 120000.00,
                'selling_price' => 110000.00,
                'tags' => json_encode(['đồ nướng', 'best-seller']),
                'unit' => 'plate',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Tôm sú hấp bia',
                'description' => 'Tôm sú tươi hấp bia, giữ nguyên vị ngọt tự nhiên.',
                'image_url' => null,
                'status' => 'active',
                'is_featured' => true,
                'category_id' => 10,
                'original_price' => 180000.00,
                'selling_price' => 170000.00,
                'tags' => json_encode(['hải sản', 'best-seller']),
                'unit' => 'plate',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Cá lóc kho tộ',
                'description' => 'Cá lóc kho tộ miền Tây, vị đậm đà.',
                'image_url' => null,
                'status' => 'active',
                'is_featured' => false,
                'category_id' => 11,
                'original_price' => 90000.00,
                'selling_price' => 85000.00,
                'tags' => json_encode(['cá các món']),
                'unit' => 'plate',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Khoai tây chiên',
                'description' => 'Khoai tây chiên giòn, ăn chơi hấp dẫn.',
                'image_url' => null,
                'status' => 'active',
                'is_featured' => true,
                'category_id' => 12,
                'original_price' => 50000.00,
                'selling_price' => 45000.00,
                'tags' => json_encode(['món ăn chơi', 'best-seller']),
                'unit' => 'plate',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Chân gà sốt Thái',
                'description' => 'Chân gà sốt Thái chua cay, giòn sần sật.',
                'image_url' => null,
                'status' => 'active',
                'is_featured' => false,
                'category_id' => 13,
                'original_price' => 80000.00,
                'selling_price' => 75000.00,
                'tags' => json_encode(['món nhậu', 'best-seller']),
                'unit' => 'plate',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Lẩu Thái hải sản',
                'description' => 'Lẩu Thái cay nồng, hải sản tươi sống.',
                'image_url' => null,
                'status' => 'active',
                'is_featured' => true,
                'category_id' => 14,
                'original_price' => 350000.00,
                'selling_price' => 320000.00,
                'tags' => json_encode(['lẩu', 'best-seller']),
                'unit' => 'plate',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Cơm chiên hải sản',
                'description' => 'Cơm chiên hải sản, thơm ngon, đầy đủ dinh dưỡng.',
                'image_url' => null,
                'status' => 'active',
                'is_featured' => false,
                'category_id' => 15,
                'original_price' => 90000.00,
                'selling_price' => 85000.00,
                'tags' => json_encode(['cơm', 'mỳ']),
                'unit' => 'plate',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
